# Generated by Django 2.2.5 on 2022-07-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0002_auto_20220705_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='period',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
