# Generated by Django 2.2.5 on 2022-07-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0003_auto_20220705_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='period_eng',
            field=models.CharField(default=-4, max_length=50),
            preserve_default=False,
        ),
    ]
