# Generated by Django 2.2.5 on 2022-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0004_subsection_period_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='period',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='period_eng',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
