# Generated by Django 2.2.5 on 2022-07-05 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0005_auto_20220705_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=256)),
                ('by_subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresume.Subsection')),
            ],
        ),
    ]
