# Generated by Django 2.2.5 on 2022-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text_eng',
            field=models.CharField(default='fuck you', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title_eng',
            field=models.CharField(default='okay', max_length=200),
            preserve_default=False,
        ),
    ]
