# Generated by Django 2.2.5 on 2022-07-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0009_auto_20220705_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('text_eng', models.CharField(max_length=512)),
                ('by_subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresume.Subsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresume.User')),
            ],
        ),
    ]
